### PR TITLE
[JENKINS-68250] Fixes PNG help icon usage.

### LINKED ISSUE #40: [JENKINS-68250] Icon defaults to help.png, which was deleted in Jenkins 2.333
_This issue is also tracked as [JENKINS-68250](https://issues.jenkins.io/browse/JENKINS-68250)._

### Jenkins and plugins versions report

I have not reproduced this bug yet, but I think it will occur when Sidebar Link 2.1.0 is used with Jenkins 2.333 or later.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Any

### Reproduction steps

1. Define a sidebar link in the global configuration, without specifying an icon.
2. Save the settings.
3. View the sidebar on the main page.

### Expected Results

The sidebar link should have a default icon.

### Actual Results

Icon won't load.

### Anything else?

PR <https://github.com/jenkinsci/sidebar-link-plugin/pull/25> made LinkAction use "static/efbf17e4/images/16x16/help.png" as the default icon. As of Sidebar Link 2.1.0, LinkAction still does so:

<https://github.com/jenkinsci/sidebar-link-plugin/blob/fa77f63045894732918b5ade79bc867e429897bd/src/main/java/hudson/plugins/sidebar_link/LinkAction.java#L67-L69>

However, <https://github.com/jenkinsci/jenkins/pull/5778> deleted `war/src/main/webapp/images/16x16/help.png` from the Jenkins core. This change was released in [Jenkins 2.333 (2022-01-31)](https://www.jenkins.io/changelog/#v2.333). The icon has been replaced with [war/src/main/webapp/images/svgs/help.svg](https://github.com/jenkinsci/jenkins/blob/f023108ec324d51d77da15890b2db8f1f76a61d3/war/src/main/webapp/images/svgs/help.svg), which was moved to that directory in <https://github.com/jenkinsci/jenkins/pull/5663> and released in [Jenkins 2.308 (2021-08-24)](https://www.jenkins.io/changelog/#v2.308).

There is a migration guide in [Icon path to icon class migration ](https://www.jenkins.io/doc/developer/views/icon-path-to-icon-class-migration/) but it looks a bit difficult to apply in the Sidebar Link plugin. I think the best fix is to save an empty string as the icon file name in the persistent configuration and substitute a version-specific default when the link is rendered. This would require separating LinkAction.getIconFileName() to two methods: one that implements Action.getIconFileName() and another that is used for the configuration UI and CasC. I hope `@Symbol` can be used to retain compatibility with existing CasC `jenkins.yaml` files.

Alternatively, Sidebar Link could ship with its own copy of `help.svg` and always default to that.

### PR DESCRIPTION
**Pull request by alecharp**
Fixes #40.
Comes with #42 and #41.

Using a recent enough version of Jenkins, the SVG files are already available, along side the PNG files. 
But, to prepare `2.333` and the PNG removal, we are now defaulting to the SVG help icon.

This won't solve the problem when users are setting the icon link to a PNG file bundled in core.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

File: src/main/java/hudson/plugins/sidebar_link/LinkAction.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public LinkAction(String urlName, String displayName, String iconFileName) throw
         }
 
         if(StringUtils.isBlank(iconFileName)) {
-            iconFileName = "static/efbf17e4/images/16x16/help.png";
+            iconFileName = "static/79e6e80a/images/svgs/help.svg";
```
Comment (NotMyFault) [inline src/main/java/hudson/plugins/sidebar_link/LinkAction.java:68]:
```suggestion
            iconFileName = "icon-help icon-md";
```
The more future proof solution would be to work with the API and call the icon class instead of relying on a path again.

File: pom.xml [hunk 2]
```diff
@@ -13,68 +13,63 @@
     <url>https://github.com/jenkinsci/sidebar-link-plugin</url>
 
     <properties>
-        <jenkins.version>2.263.4</jenkins.version>
+        <jenkins.version>2.332.2</jenkins.version>
         <java.level>8</java.level>
```
Comment (NotMyFault) [inline pom.xml:17]:
```suggestion
```
This is deprecated as of 4.40 as well and can be removed.

File: src/main/java/hudson/plugins/sidebar_link/LinkAction.java (hunk 1 above)
Comment (alecharp) [reply src/main/java/hudson/plugins/sidebar_link/LinkAction.java:68]: It's not exactly the same icon but I'm fine with it.

**Review by NotMyFault — APPROVED** [review]
Looks good so far, test failures can likely be mitigated by exchanging the path with `icon-help icon-md`.

File: src/main/java/hudson/plugins/sidebar_link/LinkAction.java [hunk 3]
```diff
@@ -65,7 +65,7 @@ public LinkAction(String urlName, String displayName, String iconFileName) throw
         }
 
         if(StringUtils.isBlank(iconFileName)) {
-            iconFileName = "static/efbf17e4/images/16x16/help.png";
+            iconFileName = "icon-help icon-md";
```
Comment (KalleOlaviNiemitalo) [inline src/main/java/hudson/plugins/sidebar_link/LinkAction.java:68]: This would cause LinkAction.getIconFileName() to return "icon-help icon-md". Such a space-delimited list doesn't seem valid according to the [documentation of Action.getIconFileName() in Jenkins 2.332.2](https://github.com/jenkinsci/jenkins/blob/jenkins-2.332.2/core/src/main/java/hudson/model/Action.java#L80-L99), which you set as the minimum version.

Comment (NotMyFault) [reply src/main/java/hudson/plugins/sidebar_link/LinkAction.java:68]: That'll work perfectly fine on the new baseline; former references the .png, latter the icon class:

Comment (KalleOlaviNiemitalo) [reply src/main/java/hudson/plugins/sidebar_link/LinkAction.java:68]: Is it documented or does it work by accident?

Comment (alecharp) [reply src/main/java/hudson/plugins/sidebar_link/LinkAction.java:68]: @NotMyFault the _current_ you are showing is also the SVG is started this PR with.
@KalleOlaviNiemitalo here https://www.jenkins.io/doc/developer/views/icon-path-to-icon-class-migration/

Comment (NotMyFault) [reply src/main/java/hudson/plugins/sidebar_link/LinkAction.java:68]: > @NotMyFault the current you are showing is also the SVG is started this PR with.

Yes, "current" mirrors your proposal, "new" is my proposed change by using the icon class..

**Comment by alecharp** [comment]
@damianszczepanik do you think this is now good enough to be merged and have a release of the plugin with this content?

File: pom.xml [hunk 4]
```diff
@@ -13,68 +13,62 @@
...
 
     <properties>
-        <jenkins.version>2.263.4</jenkins.version>
-        <java.level>8</java.level>
-        <configuration-as-code.version>1.47</configuration-as-code.version>
+        <jenkins.version>2.332.2</jenkins.version>
         <hpi.compatibleSinceVersion>2.0.0</hpi.compatibleSinceVersion>
     </properties>
 
+    <dependencyManagement>
```
Comment (damianszczepanik) [inline pom.xml:20]: Thanks for this - it was always problematic to me :)

**Comment by NotMyFault** [comment]
Thanks for merging @damianszczepanik, do you think you can cut a release anytime soon to publish the changes?

**Comment by damianszczepanik** [comment]
With I could but when trying to build locally I get following:

INFO] --- maven-hpi-plugin:3.27:insert-test (default-insert-test) @ sidebar-link ---
DEBUG] Configuring mojo org.jenkins-ci.tools:maven-hpi-plugin:3.27:insert-test from plugin realm ClassRealm[extension>org.jenkins-ci.tools:maven-hpi-
lugin:3.27, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5b37e0d2]
DEBUG] Configuring mojo 'org.jenkins-ci.tools:maven-hpi-plugin:3.27:insert-test' with basic configurator -->
DEBUG]   (f) disabledTestInjection = false
DEBUG]   (f) injectedTestName = InjectedTest
DEBUG]   (f) jenkinsTestHarnessId = org.jenkins-ci.main:jenkins-test-harness
DEBUG]   (f) project = MavenProject: org.jenkins-ci.plugins:sidebar-link:2.2.0 @ D:\git\sidebar-link-plugin\pom.xml
DEBUG]   (f) requirePI = true
DEBUG]   (f) session = org.apache.maven.execution.MavenSession@120350eb
DEBUG] -- end configuration --
INFO] ------------------------------------------------------------------------
INFO] BUILD FAILURE
INFO] ------------------------------------------------------------------------
INFO] Total time:  17.052 s
INFO] Finished at: 2022-04-21T23:27:33+02:00
INFO] ------------------------------------------------------------------------
ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.27:insert-test (default-insert-test) on project sidebar-link: Failed to create
njected tests: sidebar-link-plugin\target\generated-test-sources\injected\InjectedTest.java: Parametr is invalid. -> [Help 1]
rg.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.27:insert-test (default-insert-
est) on project sidebar-link: Failed to create injected tests
   at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)


It was working fine before 1c20c7611e44d1868aa05ec6d0689eea05aa1a18 but now even reverting this commit does not solve the problem

**Comment by damianszczepanik** [comment]
@alecharp any idea why your changes stopped me from local testing ?

**Comment by alecharp** [comment]
(sorry, no access to my laptop right now, but..)
I just tried on a fresh checkout of the PR, and didn't get any error on
`mvn verify`

Which version of Java and Maven are you using on your side? Could you try
to clean the project?

**Comment by alecharp** [comment]
I just tried again locally and I still have no problem. CI seems to be fine as well (see checks on https://github.com/jenkinsci/sidebar-link-plugin/commit/f3f8c335ca94f0fbff8e8baa032cf8c0aac87d6f)

**Comment by damianszczepanik** [comment]
Published
